/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-16 07:49:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1667367080000L));
    _jspx_dependants.put("jar:file:/Users/jinhwankim/Desktop/SpaceMusic/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/SpaceMusic/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/Users/jinhwankim/Desktop/SpaceMusic/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/SpaceMusic/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("    <title>Space Music</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap core CSS -->\n");
      out.write("    <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("    <!-- Additional CSS Files -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/fontawesome.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/templatemo-cyborg-gaming.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/owl.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animate.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/swiper@7/swiper-bundle.min.css\" />\n");
      out.write("\n");
      out.write("    <!-- Mouseover Effect CSS Files-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/mouseover.css\" />\n");
      out.write("\n");
      out.write("    <!-- modal CSS Files -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/signin.css\" />\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/YouTubePopUp.css\">\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <body>\n");
      out.write("  \n");
      out.write("  ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    <!-- ***** Preloader Start ***** -->\n");
      out.write("    <div id=\"js-preloader\" class=\"js-preloader\">\n");
      out.write("      <div class=\"preloader-inner\">\n");
      out.write("        <span class=\"dot\"></span>\n");
      out.write("        <div class=\"dots\"><span></span> <span></span> <span></span></div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- ***** Preloader End ***** -->\n");
      out.write("\n");
      out.write("    <!-- ***** Header Area Start ***** -->\n");
      out.write("    <header class=\"header-area header-sticky\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-12\">\n");
      out.write("            <nav class=\"main-nav\">\n");
      out.write("              <!-- ***** Logo Start ***** -->\n");
      out.write("              <a href=\"main.jsp\" class=\"logo\"> <img src=\"assets/images/logo.png\" alt=\"\" /> </a>\n");
      out.write("              <!-- ***** Logo End ***** -->\n");
      out.write("              <!-- ***** Search End ***** -->\n");
      out.write("              <div class=\"search-input\" style=\"width: 100%\">\n");
      out.write("                <form id=\"search\" action=\"https://www.genie.co.kr/search/searchMain?query=\">     <!-- 검색기능 --> \n");
      out.write("                  <input type=\"text\" placeholder=\"검색어 입력\" id=\"searchText\" name=\"query\" onkeypress=\"handle\" style=\"width: 100%\" />\n");
      out.write("                  <i class=\"fa fa-search\"></i>\n");
      out.write("                </form>\n");
      out.write("              </div>\n");
      out.write("              <!-- ***** Search End ***** -->\n");
      out.write("              <!-- ***** Menu Start ***** -->\n");
      out.write("              <ul class=\"nav\">\n");
      out.write("                <li class=\"dropdown\">\n");
      out.write("                  <a href=\"#\" class=\"dropdown-btn\"><span style=\"color:#e75e8d; font-weight: bold; \">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${udto.user_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> 환영합니다.<img src=\"http://localhost:8081/upload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${udto.user_picture }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\" /></a>\n");
      out.write("                  <div class=\"dropdown-submenu\">\n");
      out.write("                    <button\n");
      out.write("                      class=\"modalmenu\"\n");
      out.write("                      style=\"text-align: center; padding: 5px 60px 5px 60px; background-color: rgba(0, 0, 0, 0); border: none; color: gray\"\n");
      out.write("                      onclick=\"location.href='/getList.sm?user_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${udto.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\"\n");
      out.write("                    >\n");
      out.write("                      Popular\n");
      out.write("                    </button>\n");
      out.write("\n");
      out.write("                    <button\n");
      out.write("                      class=\"modalmenu\"\n");
      out.write("                      style=\"text-align: center; padding: 5px 60px 5px 60px; background-color: rgba(0, 0, 0, 0); border: none; color: gray\"\n");
      out.write("                      onclick=\"location.href='/getLikeSongList.sm?user_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${udto.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\"\n");
      out.write("                      ;\n");
      out.write("                    >\n");
      out.write("                      My Menu\n");
      out.write("                    </button>\n");
      out.write("\n");
      out.write("                    <button\n");
      out.write("                      class=\"modalmenu\"\n");
      out.write("                      style=\"text-align: center; padding: 5px 60px 5px 60px; background-color: rgba(0, 0, 0, 0); border: none; color: gray\"\n");
      out.write("                      onclick=\"location.href='index.jsp'\"\n");
      out.write("                    >\n");
      out.write("                      Logout\n");
      out.write("                    </button>\n");
      out.write("                  </div>\n");
      out.write("                </li>\n");
      out.write("              </ul>\n");
      out.write("              <a class=\"menu-trigger\"> <span>Menu</span> </a>\n");
      out.write("              <!-- ***** Menu End ***** -->\n");
      out.write("            </nav>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- ***** Header Area End ***** -->\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-lg-12\">\n");
      out.write("          <div class=\"page-content\">\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"slidebn slidebn_wrap\">\n");
      out.write("              <div class=\"slidebn_item item1\"></div>\n");
      out.write("              <div class=\"slidebn_item item2\">2</div>\n");
      out.write("              <div class=\"slidebn_item item3\">3</div>\n");
      out.write("<!--               <div class=\"slidebn_item item4\">4</div> -->\n");
      out.write("<!--               <div class=\"slidebn_item item5\">5</div> -->\n");
      out.write("              <div class=\"slidebn_prev_button slidebn_button\">◀</div>\n");
      out.write("              <div class=\"slidebn_next_button slidebn_button\">▶</div>\n");
      out.write("              <ul class=\"slidebn_pagination\"></ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- ***** Most Popular Start ***** -->\n");
      out.write("            <div class=\"most-popular\">\n");
      out.write("              <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                  <div class=\"heading-section\">\n");
      out.write("                    <h4><em>장르별</em> 음악</h4>\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                      <div class=\"item\">\n");
      out.write("                        <img class=\"my_img\" src=\"assets/images/popular-01.png\" style=\"cursor: pointer\" onclick=\"location.href='/getListByGenre.sm?genre_id=1&user_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${udto.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" />\n");
      out.write("                        <!--                                  <h4>발라드</h4> -->\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                      <div class=\"item\">\n");
      out.write("                        <img class=\"my_img\" src=\"assets/images/popular-02.png\" style=\"cursor: pointer\" onclick=\"location.href='/getListByGenre.sm?genre_id=2&user_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${udto.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" />\n");
      out.write("                        <!--                                  <h4>댄스</h4> -->\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                      <div class=\"item\">\n");
      out.write("                        <img class=\"my_img\" src=\"assets/images/popular-03.png\" style=\"cursor: pointer\" onclick=\"location.href='/getListByGenre.sm?genre_id=3&user_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${udto.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" />\n");
      out.write("                        <!--                                  <h4>랩/힙합</h4> -->\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                      <div class=\"item\">\n");
      out.write("                        <img class=\"my_img\" src=\"assets/images/popular-04.png\" style=\"cursor: pointer\" onclick=\"location.href='/getListByGenre.sm?genre_id=4&user_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${udto.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" />\n");
      out.write("                        <!--                                  <h4>R&B/Soul</h4> -->\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                      <div class=\"item\">\n");
      out.write("                        <img class=\"my_img\" src=\"assets/images/popular-05.png\" style=\"cursor: pointer\" onclick=\"location.href='/getListByGenre.sm?genre_id=5&user_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${udto.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" />\n");
      out.write("                        <!--                                  <h4>인디음악</h4> -->\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                      <div class=\"item\">\n");
      out.write("                        <img class=\"my_img\" src=\"assets/images/popular-06.png\" style=\"cursor: pointer\" onclick=\"location.href='/getListByGenre.sm?genre_id=6&user_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${udto.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" />\n");
      out.write("                        <!--                                  <h4>록/메탈</h4> -->\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                      <div class=\"item\">\n");
      out.write("                        <img class=\"my_img\" src=\"assets/images/popular-07.png\" style=\"cursor: pointer\" onclick=\"location.href='/getListByGenre.sm?genre_id=7&user_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${udto.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" />\n");
      out.write("                        <!--                                  <h4>트로트</h4> -->\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                      <div class=\"item\">\n");
      out.write("                        <img class=\"my_img\" src=\"assets/images/popular-08.png\" style=\"cursor: pointer\" onclick=\"location.href='/getListByGenre.sm?genre_id=8&user_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${udto.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" />\n");
      out.write("                        <!--                                  <h4>포크/블루스</h4> -->\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- <div class=\"col-lg-12\">\n");
      out.write("                    <div class=\"main-button\">\n");
      out.write("                      <a href=\"browse.html\">인기차트 바로가기</a>\n");
      out.write("                    </div>\n");
      out.write("                  </div> -->\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- ***** Most Popular End ***** -->\n");
      out.write("\n");
      out.write("            <!-- ***** Gaming Library Start ***** -->\n");
      out.write("            <!--\n");
      out.write("          <div class=\"gaming-library\">\n");
      out.write("            <div class=\"col-lg-12\">\n");
      out.write("              <div class=\"heading-section\">\n");
      out.write("                <h4><em>나의</em> 재생목록</h4>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"item\">\n");
      out.write("                <ul>\n");
      out.write("                  <li><img src=\"assets/images/game-01.jpg\" alt=\"\" class=\"templatemo-item\"></li>\n");
      out.write("                  <li><h4>제로투</h4><span>김남수</span></li>\n");
      out.write("                  <li><h4>Date Added</h4><span>24/08/2036</span></li>\n");
      out.write("                  <li><h4>Hours Played</h4><span>634 H 22 Mins</span></li>\n");
      out.write("                  <li><h4>Currently</h4><span>Downloaded</span></li>\n");
      out.write("                  <li><div class=\"main-border-button border-no-active\"><a href=\"#\">Donwloaded</a></div></li>\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"item\">\n");
      out.write("                <ul>\n");
      out.write("                  <li><img src=\"assets/images/game-02.jpg\" alt=\"\" class=\"templatemo-item\"></li>\n");
      out.write("                  <li><h4>Dynamite</h4><span>방탄소년단</span></li>\n");
      out.write("                  <li><h4>Date Added</h4><span>22/06/2036</span></li>\n");
      out.write("                  <li><h4>Hours Played</h4><span>740 H 52 Mins</span></li>\n");
      out.write("                  <li><h4>Currently</h4><span>Downloaded</span></li>\n");
      out.write("                  <li><div class=\"main-border-button\"><a href=\"#\">Donwload</a></div></li>\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"item last-item\">\n");
      out.write("                <ul>\n");
      out.write("                  <li><img src=\"assets/images/game-03.jpg\" alt=\"\" class=\"templatemo-item\"></li>\n");
      out.write("                  <li><h4>CS-GO</h4><span>Sandbox</span></li>\n");
      out.write("                  <li><h4>Date Added</h4><span>21/04/2036</span></li>\n");
      out.write("                  <li><h4>Hours Played</h4><span>892 H 14 Mins</span></li>\n");
      out.write("                  <li><h4>Currently</h4><span>Downloaded</span></li>\n");
      out.write("                  <li><div class=\"main-border-button border-no-active\"><a href=\"#\">Donwloaded</a></div></li>\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-12\">\n");
      out.write("              <div class=\"main-button\">\n");
      out.write("                <a href=\"profile.html\">View Your Library</a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div> -->\n");
      out.write("            <!-- ***** Gaming Library End ***** -->\n");
      out.write("            <!-- ***** Featured Games Start ***** -->\n");
      out.write("        <br>\n");
      out.write("        <br>\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-8\">\n");
      out.write("              <div class=\"featured-games header-text\">\n");
      out.write("                <div class=\"heading-section\">\n");
      out.write("                  <h4>최신음악</h4>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"owl-features owl-carousel\">\n");
      out.write("                  <div class=\"item\">\n");
      out.write("                    <div class=\"thumb\">\n");
      out.write("                      <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/110/89/457/11089457_20221028103340_500.jpg?8ca61a6bb95214f0575178534df6fd04/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                    <h4>The Astronaut<br><span>jin</span></h4>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"item\">\n");
      out.write("                    <div class=\"thumb\">\n");
      out.write("                      <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/110/62/364/11062364_20220922182518_500.jpg?a57bb5b9e4a17ceaf47edfdc088ad8ec/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                    <h4>Rush Hour<br><span>Crush</span></h4>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"item\">\n");
      out.write("                    <div class=\"thumb\">\n");
      out.write("                      <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/110/78/852/11078852_20221017102947_500.jpg?3afd315fe8957d40a511b9c42aeaf516/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                    <h4>I love<br><span>(여자)아이들</span></h4>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"item\">\n");
      out.write("                    <div class=\"thumb\">\n");
      out.write("                      <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/110/78/496/11078496_20221014153848_500.jpg?90c93d5c7f38394169a4c5c70683eb0b/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                    <h4>ANTIFRAGILE<br><span>LE SSERAFIM (르세라핌)</span></h4>\n");
      out.write("\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"item\">\n");
      out.write("                    <div class=\"thumb\">\n");
      out.write("                      <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/109/03/868/10903868_20220330103544_500.jpg?e89c53bde5d39b21b09e8007db5b9cc0/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                    <h4>YOUNHA 6th Album Repackage 'END THEORY : Final Edition'<br><span>윤하 (YOUNHA)</span></h4>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"item\">\n");
      out.write("                    <div class=\"thumb\">\n");
      out.write("                      <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/109/37/474/10937474_20220428225312_500.jpg?cbc115ca0a2db2fed082e94f5862e8bd/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                    </div>\n");
      out.write("                    <h4>싸다9<br><span>싸이 (PSY)</span></h4>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-4\">\n");
      out.write("              <div class=\"top-streamers\">\n");
      out.write("                <div class=\"heading-section\">\n");
      out.write("                  <h4>TOP 100</h4>\n");
      out.write("                </div>\n");
      out.write("                <ul>\n");
      out.write("                  <li>\n");
      out.write("                    <span>01</span>\n");
      out.write("                    <img src=\"https://cdnimg.melon.co.kr/cm2/album/images/110/89/457/11089457_20221028103340_500.jpg?8ca61a6bb95214f0575178534df6fd04/melon/resize/282/quality/80/optimize\" alt=\"\" style=\"max-width: 46px; border-radius: 50%; margin-right: 15px;\">\n");
      out.write("                    <h6>jin</h6>\n");
      out.write("                    <div class=\"main-button\">\n");
      out.write("                      <i class=\"fa-solid fa-music\"></i>\n");
      out.write("                      <a class=\"bla-1\" href=\"https://www.youtube.com/watch?v=fheWlRUjnY4\" i class=\"fi fi-sr-play\" >듣기</a>\n");
      out.write("                    </div>\n");
      out.write("                  </li>\n");
      out.write("                  <li>\n");
      out.write("                    <span>02</span>\n");
      out.write("                    <img src=\"https://cdnimg.melon.co.kr/cm2/album/images/109/89/806/10989806_20220623153505_500.jpg?35a4d0f2d14ee902dfab94e04a817303/melon/resize/282/quality/80/optimize\" alt=\"\" style=\"max-width: 46px; border-radius: 50%; margin-right: 15px;\">\n");
      out.write("                    <h6>Charlie Puth With 정국</h6>\n");
      out.write("                    <div class=\"main-button\">\n");
      out.write("                      <a class=\"bla-1\" href=\"https://www.youtube.com/watch?v=a7GITgqwDVg\" i class=\"fi fi-sr-play\" >듣기</a>\n");
      out.write("                    </div>\n");
      out.write("                  </li>\n");
      out.write("                  <li>\n");
      out.write("                    <span>03</span>\n");
      out.write("                    <img src=\"https://cdnimg.melon.co.kr/cm2/album/images/110/78/496/11078496_20221014153848_500.jpg?90c93d5c7f38394169a4c5c70683eb0b/melon/resize/282/quality/80/optimize\" alt=\"\" style=\"max-width: 46px; border-radius: 50%; margin-right: 15px;\">\n");
      out.write("                    <h6>LE SSERAFIM</h6>\n");
      out.write("                    <div class=\"main-button\">\n");
      out.write("                      <a class=\"bla-1\" href=\"https://www.youtube.com/watch?v=ZNEuWldWPD4\" i class=\"fi fi-sr-play\" >듣기</a>\n");
      out.write("                    </div>\n");
      out.write("                  </li>\n");
      out.write("                  <li>\n");
      out.write("                    <span>04</span>\n");
      out.write("                    <img src=\"https://cdnimg.melon.co.kr/cm2/album/images/110/34/298/11034298_20220822101843_500.jpg?d34a229786bda1750cf7718abdc6b869/melon/resize/282/quality/80/optimize\" alt=\"\" style=\"max-width: 46px; border-radius: 50%; margin-right: 15px;\">\n");
      out.write("                    <h6>IVE (아이브)</h6>\n");
      out.write("                    <div class=\"main-button\">                \n");
      out.write("                       <a class=\"bla-1\" href=\"https://www.youtube.com/watch?v=F0B7HDiY-10\" i class=\"fi fi-sr-play\" >듣기</a>\n");
      out.write("                    </div>\n");
      out.write("                  </li>\n");
      out.write("                  <li>\n");
      out.write("                    <span>05</span>\n");
      out.write("                    <img src=\"https://cdnimg.melon.co.kr/cm2/album/images/109/03/868/10903868_20220330103544_500.jpg?e89c53bde5d39b21b09e8007db5b9cc0/melon/resize/282/quality/80/optimize\" alt=\"\" style=\"max-width: 46px; border-radius: 50%; margin-right: 15px;\">\n");
      out.write("                    <h6>윤하 (YOUNHA)</h6>\n");
      out.write("                    <div class=\"main-button\">\n");
      out.write("                      <a class=\"bla-1\" href=\"https://www.youtube.com/watch?v=BBdC1rl5sKY\" i class=\"fi fi-sr-play\" >듣기</a>\n");
      out.write("                    </div>\n");
      out.write("                    <br><br>\n");
      out.write("                    <div style=\"text-align: center;\">\n");
      out.write("                    <button style=\"text-align: center; padding: 5px 60px 5px 60px; background-color: #1f2122; color: #f99; border-radius: 30px; border-color: black;\"\n");
      out.write("                            onclick=\"location.href='/getList.sm?user_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${udto.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">더 보기</button>\n");
      out.write("                    </div>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <!-- ***** Featured Games End ***** -->\n");
      out.write("\n");
      out.write("          <!-- ***** Live Stream Start ***** -->\n");
      out.write("          \n");
      out.write("          <div class=\"live-stream\">\n");
      out.write("            <div class=\"col-lg-12\">\n");
      out.write("              <div class=\"heading-section\">\n");
      out.write("                <h4>인기뮤직비디오</h4>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("             <div class=\"row\">\n");
      out.write("         \n");
      out.write("         \n");
      out.write("              <!--01-->\n");
      out.write("              <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                <div class=\"item\">\n");
      out.write("                  <div class=\"thumb\">\n");
      out.write("                    <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/110/78/852/11078852_20221017102947_500.jpg?3afd315fe8957d40a511b9c42aeaf516/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                     <div class=\"hover-effect\">\n");
      out.write("                      <div class=\"content\">\n");
      out.write("                        <div class=\"live\">\n");
      out.write("                          <a class=\"bla-1\" href=\"https://youtu.be/fCO7f0SmrDc\" target=\"_blank\"><i class=\"fa fa-play\"></i></a>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"down-content\">\n");
      out.write("                    <div class=\"item\">\n");
      out.write("                    <div class=\"avatar\">\n");
      out.write("                      <img src=\"https://cdnimg.melon.co.kr/cm2/artistcrop/images/021/37/482/2137482_20221017115456_500.jpg?c1fe5219fa5df67e5a62677b42384e5c/melon/resize/416/quality/80/optimize\" alt=\"\" style=\"max-width: 46px; border-radius: 50%; float: left;\">\n");
      out.write("                    </div>\n");
      out.write("                    <span><i class=\"fa fa-music\"></i>(여자)아이들</span>\n");
      out.write("                    <h4>I love</h4>\n");
      out.write("                  </div> \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("              <!--02-->\n");
      out.write("              <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                <div class=\"item\">\n");
      out.write("                  <div class=\"thumb\">\n");
      out.write("                    <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/104/79/150/10479150_20200918102847_500.jpg?45d847d7dc536eecebd648786c2ea37c/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                    <div class=\"hover-effect\">\n");
      out.write("                      <div class=\"content\">\n");
      out.write("                        <div class=\"live\">\n");
      out.write("                          <a class=\"bla-1\" href=\"https://youtu.be/gdZLi9oWNZg\" target=\"_blank\"><i class=\"fa fa-play\"></i></a>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"down-content\">\n");
      out.write("                    <div class=\"avatar\">\n");
      out.write("                      <img src=\"https://cdnimg.melon.co.kr/cm2/artistcrop/images/006/72/375/672375_20220610104703_500.jpg?4d3ac0fb5368764c77e6e26dda78b180/melon/resize/416/quality/80/optimize\" alt=\"\" style=\"max-width: 46px; border-radius: 50%; float: left;\">\n");
      out.write("                    </div>\n");
      out.write("                    <span><i class=\"fa fa-music\"></i>방탄소년단</span>\n");
      out.write("                    <h4>Dynamite</h4>\n");
      out.write("                  </div> \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <!--03-->\n");
      out.write("              <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                <div class=\"item\">\n");
      out.write("                  <div class=\"thumb\">\n");
      out.write("                    <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/110/89/457/11089457_20221028103340_500.jpg?8ca61a6bb95214f0575178534df6fd04/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                    <div class=\"hover-effect\">\n");
      out.write("                      <div class=\"content\">\n");
      out.write("                        <div class=\"live\">\n");
      out.write("                          <a class=\"bla-1\" href=\"https://youtu.be/c6ASQOwKkhk\" target=\"_blank\"><i class=\"fa fa-play\"></i></a>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"down-content\">\n");
      out.write("                    <div class=\"avatar\">\n");
      out.write("                      <img src=\"https://cdnimg.melon.co.kr/cm2/artistcrop/images/007/25/986/725986_20221024120819_500.jpg?f23de1d5a34afc9905b1c6d4d438e308/melon/resize/416/quality/80/optimize\" alt=\"\" style=\"max-width: 46px; border-radius: 50%; float: left;\">\n");
      out.write("                    </div>\n");
      out.write("                    <span><i class=\"fa fa-music\"></i>jin</span>\n");
      out.write("                    <h4>The Astronaut</h4>\n");
      out.write("                  </div> \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <!--04-->\n");
      out.write("              <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                <div class=\"item\">\n");
      out.write("                  <div class=\"thumb\">\n");
      out.write("                    <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/106/12/483/10612483_20210521111412_500.jpg?1c2769f71815b15741622b61a75fb530/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                    <div class=\"hover-effect\">\n");
      out.write("                      <div class=\"content\">\n");
      out.write("                        <div class=\"live\">\n");
      out.write("                          <a class=\"bla-1\" href=\"https://youtu.be/WMweEpGlu_U\" target=\"_blank\"><i class=\"fa fa-play\"></i></a>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"down-content\">\n");
      out.write("                    <div class=\"avatar\">\n");
      out.write("                      <img src=\"https://cdnimg.melon.co.kr/cm2/artistcrop/images/006/72/375/672375_20220610104703_500.jpg?4d3ac0fb5368764c77e6e26dda78b180/melon/resize/416/quality/80/optimize\" alt=\"\" style=\"max-width: 46px; border-radius: 50%; float: left;\">\n");
      out.write("                    </div>\n");
      out.write("                    <span><i class=\"fa fa-music\"></i>방탄소년단</span>\n");
      out.write("                    <h4>Butter</h4>\n");
      out.write("                  </div> \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <!--05-->\n");
      out.write("              <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                <div class=\"item\">\n");
      out.write("                  <div class=\"thumb\">\n");
      out.write("                    <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/110/34/298/11034298_20220822101843_500.jpg?d34a229786bda1750cf7718abdc6b869/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                    <div class=\"hover-effect\">\n");
      out.write("                      <div class=\"content\">\n");
      out.write("                        <div class=\"live\">\n");
      out.write("                          <a class=\"bla-1\" href=\"https://youtu.be/F0B7HDiY-10\" target=\"_blank\"><i class=\"fa fa-play\"></i></a>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                    <div class=\"down-content\">\n");
      out.write("                    <div class=\"avatar\">\n");
      out.write("                      <img src=\"https://cdnimg.melon.co.kr/cm2/artistcrop/images/030/55/146/3055146_20220822140953_500.jpg?09a40395f6fbbcf9859d280eee357e7f/melon/resize/416/quality/80/optimize\" alt=\"\" style=\"max-width: 46px; border-radius: 50%; float: left;\">\n");
      out.write("                    </div>\n");
      out.write("                    <span><i class=\"fa fa-music\"></i>IVE (아이브)</span>\n");
      out.write("                    <h4>After LIKE</h4>\n");
      out.write("                  </div> \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <!--06-->\n");
      out.write("              <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                <div class=\"item\">\n");
      out.write("                  <div class=\"thumb\">\n");
      out.write("                    <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/110/11/565/11011565_20220801102637_500.jpg?1d674a44faffa0ebd34d86c182463171/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                    <div class=\"hover-effect\">\n");
      out.write("                      <div class=\"live\">\n");
      out.write("                      <div class=\"content\">\n");
      out.write("                          <a class=\"bla-1\" href=\"https://youtu.be/VOmIplFAGeg\" target=\"_blank\"><i class=\"fa fa-play\"></i></a>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"down-content\">\n");
      out.write("                    <div class=\"avatar\">\n");
      out.write("                      <img src=https://cdnimg.melon.co.kr/cm2/artistcrop/images/031/14/174/3114174_20220801095554_500.jpg?6ad95871305f927dac3c4b5e835dca5a/melon/resize/416/quality/80/optimize\" alt=\"\" style=\"max-width: 46px; border-radius: 50%; float: left;\">\n");
      out.write("                    </div>\n");
      out.write("                    <span><i class=\"fa fa-music\"></i>NewJeans</span>\n");
      out.write("                    <h4>Cookie</h4>\n");
      out.write("                  </div> \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <!--07-->\n");
      out.write("              <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                <div class=\"item\">\n");
      out.write("                  <div class=\"thumb\">\n");
      out.write("                    <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/108/44/485/10844485_20221006154824_500.jpg?b752b5ed8fad66b79e2705840630dd94/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                    <div class=\"hover-effect\">\n");
      out.write("                      <div class=\"content\">\n");
      out.write("                        <div class=\"live\">\n");
      out.write("                          <a class=\"bla-1\" href=\"https://youtu.be/Nq3x1AkwgpY\" target=\"_blank\"><i class=\"fa fa-play\"></i></a>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"down-content\">\n");
      out.write("                    <div class=\"avatar\">\n");
      out.write("                      <img src=\"https://cdnimg.melon.co.kr/cm2/artistcrop/images/008/38/654/838654_20220411094354_500.jpg?3703649606d8df48d444851e39f3528f/melon/resize/416/quality/80/optimize\" alt=\"\" style=\"max-width: 46px; border-radius: 50%; float: left;\">\n");
      out.write("                    </div>\n");
      out.write("                    <span><i class=\"fa fa-music\"></i>Charlie Puth</span>\n");
      out.write("                    <h4>That's Hilarious</h4>\n");
      out.write("                  </div> \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <!--08-->\n");
      out.write("              <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("                <div class=\"item\">\n");
      out.write("                  <div class=\"thumb\">\n");
      out.write("                    <img class= \"my_img\" src=\"https://cdnimg.melon.co.kr/cm2/album/images/107/43/453/10743453_20211018165252_500.jpg?4a230414088a35eeff232020daf65806/melon/resize/282/quality/80/optimize\" alt=\"\">\n");
      out.write("                    <div class=\"hover-effect\">\n");
      out.write("                      <div class=\"content\">\n");
      out.write("                        <div class=\"live\">\n");
      out.write("                          <a class=\"bla-1\" href=\"https://youtu.be/sqgxcCjD04s\" target=\"_blank\"><i class=\"fa fa-play\"></i></a>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"down-content\">\n");
      out.write("                    <div class=\"avatar\">\n");
      out.write("                      <img src=\"https://cdnimg.melon.co.kr/cm2/artistcrop/images/002/61/143/261143_20210325180240_500.jpg?61e575e8653e5920470a38d1482d7312/melon/resize/416/quality/80/optimize\" alt=\"\" style=\"max-width: 46px; border-radius: 50%; float: left;\">\n");
      out.write("                    </div>\n");
      out.write("                    <span><i class=\"fa fa-music\"></i>아이유</span>\n");
      out.write("                    <h4>strawberry moon</h4>\n");
      out.write("                  </div> \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("    <div style=\"position: fixed; bottom: 20px; right: 10px; width: 50px;\">\n");
      out.write("      <a href=\"#\"><img src=\"https://cdn-icons-png.flaticon.com/128/4160/4160970.png\"> </a>\n");
      out.write("   </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <footer>\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-lg-12\">\n");
      out.write("            <p><a>Copyright © 2022 Korea IT Academy</a> <a>잘하는데, 이조?</a> All rights reserved.</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <!-- Scripts -->\n");
      out.write("    <!-- Bootstrap core JavaScript -->\n");
      out.write("    <script src=\"vendor/jquery/jquery.min.js\"></script>\n");
      out.write("    <script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"assets/js/isotope.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/owl-carousel.js\"></script>\n");
      out.write("    <script src=\"assets/js/tabs.js\"></script>\n");
      out.write("    <script src=\"assets/js/popup.js\"></script>\n");
      out.write("    <script src=\"assets/js/custom.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- <script src=\"assets/js/modal.js\"></script> -->\n");
      out.write("    <script src=\"assets/js/signIn.js\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"assets/js/mainbanner.js\"></script>\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\" src=\"assets/js/jquery-1.12.1.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"assets/js/YouTubePopUp.jquery.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /main.jsp(35,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("udto");
      // /main.jsp(35,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applicationScope.udto }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
